### ISSUE TITLE
The board/ict wants to register/de-regiser people from an activity

### ISSUE THREAD

**Issue by cpbscholten** [csvalpha/amber-api#13]
Copied from alpha-banana-api (dutch):

@cmitz Later even aanvullen, nu op startweekend
@tcoenraad Dat is een vrij logische feature om te hebben. Als we naar een zelfafrekend systeem toe willen ook noodzakelijk. Omdat dit iets is wat je niet zelf initieert is het wel belangrijk om de gebruiker (per mail?) te informeren hierover.
@cmitz Twan oppert op de vergadering van 19 februari:

    Als het mogelijk is dat een bestuurder ineens iemand kan inschrijven, is het niet meer een bewuste actie van de gebruiker. Dan wil ik graag een bevestiging per mail.
    En een overzicht op de website met "Mijn inschrijvingen"?
@Matthijsy Is dit iets wat gebruikt gaat worden? Is prima mogelijk om te bouwen maar denk dat een zelfafrekend systeem hem bij Alpha niet gaat worden. Daarbij wordt er op de activiteit vaak toch een nieuw lijstje gemaakt en ben ik bang dat bestuurders dat niet nog op de stek gaan verwerken.
@cmitz Ja! Ik zou het sowieso willen doen om een sluitend systeem wel mogelijk te maken voor de toekomst. En op hetzelfde vlak, ik zou ook nog mijn inschrijving willen aanpassen als de datum nog niet verstreken is....

**Comment by Matthijsy** [comment]
I am still not sure if this will be used. It would be a good idea to poll this feature at the board and maybe some comittees before implementing. Would you agree?

**Comment by Matthijsy** [comment]
Not asked for since a really long time, closing payment system will probably not be implemented in the short future so closing it for now
