### ISSUE TITLE
Production environment always uses summertime

### ISSUE THREAD

**Issue by Matthijsy** [csvalpha/amber-api#192]
### How to reproduce
1. Run `Time.zone.now` on production, or check the Ical data

### Expected behaviour
It is in the current timezone

### Current behaviour
It is still in the summer time. Could probably be fixed by setting the timezone in the dockerfile

**Comment by guidojw** [comment]
Yeah my whole Alpha calendar on Google is shifted one hour. 

Would this be fixed by setting 
`TZ=Europe/Amsterdam`
in the .env file in /opt/docker/amber-api/production?

**Comment by Matthijsy** [comment]
Yes that would probably fix it!

**Comment by Matthijsy** [comment]
We did fix this, don't remember anymore how but was something related to a gem update
