### ISSUE TITLE
Nextcould integration

### ISSUE THREAD

**Issue by cpbscholten** [csvalpha/amber-api#3]
Copied from alpha-banana-api (dutch):

Het is weer eens tijd voor een nieuw epic, dus hierbij. Het lijkt me tof om een nextcloud integratie te maken aangezien we dan een groot centraal archief kunnen bouwen en dingen ook meer GDPR proof kunnen maken. Dit issue is bedoeld om te bepalen of het nuttig is om het op te zetten en om een design te maken voordat we het gaan implementeren. Ik heb geprobeerd alles met MoSCoW te labelen.

##Functioneel
Ik denk aan de volgende functionele requirements:

1. Single Sign on (should) of op z'n minst inlog met dezelfde gegevens (must)
1. Automatische groepen synchronisatie (must) (bij inlog dan wel via een sync systeem)
1. Automatisch toegang tot mappen van oud-commissies/bestuur (should) en het kunnen maken/hebben van jaar specifieke map van commissie/bestuur
1. Alleen read toegang tot mappen van oud-commissies/bestuur (could)
1. Goede desktop/mobile app (should)
1. Geen tot weinig administratief werk voor het bestuur

Ik denk dat de meeste van deze punten goed uit te werken is. Als we punt 1 en 2 uitvoeren komt punt 3 er als het goed is vanzelf bij via de werkwijze van nextcloud. Punt 4 weet ik niet hoe haalbaar het is maar zou opzich wel tof zijn. Punt 5 zouden we even moeten checken maar als het goed is heeft nextcloud prima ondersteuningen. Punt 6 volgt uit de voorgaande punten, behalve als ik nog wat over het hoofd heb gezien ;)

## Implementatie
Ik denk dat kwa implementatie het lastigste de SSO wordt. We ondersteunen dit al wel maar moeten dit nog verder uitbreiden. Ik stel daarom ook de volgende wijzigingen voor.

###ApplicationPermissions (should)
Ik denk dat we application permissions moeten implementeren zodat we niet elke keer als een applicatie meer toegang nodig heeft we hiervoor in de code hoeven te duiken. Ik denk hierbij aan een model wat gekoppeld is aan een Doorkeeper::Application en wat een name heeft in de vorm model.attribute. Ik heb hier specifiek gekozen voor attribute aangezien een applicatie vaak maar zeer specifiek toegang nodig heeft en (tot nu toe) nog nooit iets anders dan read nodig heeft.

###Update van toesteming pagina (UI)(must)
We moeten de UI pagina updaten zodat hij zegt voor welke specifieke applicatie je toestemming geeft. Daarbij kunnen we dan ook de ApplicationPermissions laten zien zodat de gebruiker direct weet welke gegevens hij deelt.

### ApplicationGrants (could)
Als we vervolgens ook een ApplicationsGrants model maken dan kunnen we bijhouden wie er al een keer heeft ingelogd en hoefen die mensen dus geen toestemming meer te geven.
/users/me/nextcloud endpoint maken (must)

De sociallogin app die ik gebruikte om de sso in nextcloud te hangen verwacht net een ander dataformat dan dat onze api geeft. Daarom moeten we een specifiek nextcloud endpoint maken

### Group sync maken (must)
De sociallogin plugin die ik gebruikte ondersteund geen group sync. Ik denk dat we het beste een Nextcloud plugin kunnen maken (dat gaat helaas wel php zijn) die dit ondersteund. Dit zou een lostaande app kunnen zijn maar ik denk dat het wel toffer is om het te implementeren binnen de social login app. Wat voor de community betekenen is altijd tof!

Ik denk dat dit ongeveer is wat er nodig is. Natuurlijk moeten we niet vergeten om eerst te kijken of we het uberhaupt willen, dus het lijkt me goed eerst een discussie te hebben voordat we dingen gaan bouwen. Daarbij maken bovenstaande aanpassingen onze oauth2 ook completer waardoor we in de toekomst ook meer SSO of andere oauth applicaties kunnen gaan ondersteunen. Ik hoor graag wat jullie ideen zijn en of ik nog functionele dan wel technische dingen heb gemist.

**Comment by Matthijsy** [comment]
Done!
