### ISSUE TITLE
Activity mail alias not working with more than 50 signups

### ISSUE THREAD

**Issue by wilco375** [csvalpha/amber-api#370]
### How to reproduce
1. Create an activity with a signup list
2. Have more than 50 participants
3. Create a new mail alias

### Expected behaviour
Mail alias is created

### Current behaviour
ImprovMX returns: `Improvmx::BadRequestError: 400 Bad Request {"forward"=>["You can only add up to 50 destinations. If you need more, please contact us."]}`

### Possible solutions
There is not really a clean solution for this limitation I think. Two possible solutions I see:
1. Create a mail alias for each group of 50 participants and display the multiple aliases to the user
2. Create a mail alias for each group of 50 participants, and then create an additional alias that has the other aliases as the recipients

**Comment by lodewiges** [comment]
I think This issue is solved, because the limit is increased to 100 people which is unlikely to be surpassed on a activity, otherwise you could force moderation on mailadres with more than 100 people
