### ISSUE TITLE
Mailing list sync is broken

### ISSUE THREAD

**Issue by wilco375** [csvalpha/amber-api#389]
See csvapha.nl/sidekiq, updating requests to ImprovMX generate an error and are not processed. For example, two new members of the RvT group have not been synced with the RvT mailing list alias.

**Comment by DrumsnChocolate** [comment]
I have no clue where to start looking for the problem. It does not seem likely that the ImprovMX API changed, so what exactly did change?

**Comment by wilco375** [comment]
Yeah that's a good question... Maybe check if there were any deploys around the time the issue started. And try to get the full error response of the ImprovMX API call, that might give some info on what's going wrong.

**Comment by DrumsnChocolate** [comment]
fixed by #392
