### ISSUE TITLE
Article pinning

### ISSUE THREAD

**Issue by cpbscholten** [csvalpha/amber-api#4]
Copied from alpha-banana-api (dutch):
Het zou handig zijn als je een artikel (tijdelijk) verder omhoog kan zetten. Dit zouden we kunnen doen met een prioriteits flag. We zouden 2 fields kunnen toevoegen: priority en priority_untill. Dan zouden we een sort kunnen maken die het artikel met de hoogste priority die nog valid is (current_time < priority_untill) bovenaan zet.

@Matthijsy: Update van de vergadering van 26-03. Het idee is om 1 artikel te kunnen pinnen. Het idee is dan om een pinned_untill veld toe te voegen. Maar 1 artikel mag dan tegelijk gepinned zijn.

**Comment by Matthijsy** [comment]
@guidojw Do you have an update on this?

**Comment by guidojw** [comment]
@Matthijsy Not currently.
A couple of weeks ago I've been looking into learning the basics of Ember and now module 8 is requiring a lot of my attention. I'll try to make some space for this in the coming weeks.
