### ISSUE TITLE
Remove quickpost

### ISSUE THREAD

**Issue by DrumsnChocolate** [csvalpha/amber-api#404]
The quickpost once was a feature that was very nice to use, and added value for most users. In the past years, it has become outdated in its implementation, accumulated bugs, and many members report seeing little benefit to the feature. There are widely used alternatives like WhatsApp that are more complete and at least as easy to use, making the quickpost obsolete. It makes sense to remove this, since it is a technical burden that does not seem worth the cost of fixing or maintaining.

**Comment by lodewiges** [comment]
has this been done already?

**Comment by DrumsnChocolate** [comment]
not entirely. We're simply not showing it on people's screens, i.e. we've removed it from the templates in amber-ui (mostly. it still is accessible though: https://csvalpha.nl/quickpost but it's broken and not used by anyone in almost a year) but we have not removed other parts. other parts include some parts in amber-ui, and some parts here in amber-api
