### ISSUE TITLE
Photo tag deleted when user is archived

### ISSUE THREAD

**Issue by wilco375** [csvalpha/amber-api#426]
As seen in the user archive job spec (https://github.com/csvalpha/amber-api/blob/3da617670ad7a32dc533285760e91d70bf4a9e90/spec/jobs/user_archive_job_spec.rb#L60) both tags of the user and created by the user to be archived are deleted. Although the first is logical, since an archived user could otherwise be identified from pictures and associated to the profile again, tags created by the user should actually not be deleted, but be assigned to archive_user as happens for instance with photos they uploaded

**Comment by lodewiges** [comment]
archiving has been broken for 2 years as far as I know so, this is not yet an issue

**Comment by wilco375** [comment]
> archiving has been broken for 2 years as far as I know so, this is not yet an issue (#428)
> 

In that case archiving should be fixed too too to conform to the GDPR
