### ISSUE TITLE
Public comments not loaded correctly

### ISSUE THREAD

**Issue by cpbscholten** [csvalpha/amber-api#6]
### How to reproduce
1. Go signied in to https://csvalpha.nl/photo-albums/44/photos/2325
2. Go signed out to https://csvalpha.nl/photo-albums/44/photos/2325

The same happens for public articles

### Expected behaviour
Both should show the same comments

### Current behaviour
Server sends a 401 unauthorized on the photocomment
Server sends a 401 unauthorized on the 'related' users at public article comments

**Comment by Matthijsy** [comment]
Fixed in #147
