### ISSUE TITLE
Plan emails

### ISSUE THREAD

**Issue by wilco375** [csvalpha/amber-api#71]
I would like to have the option to, when moderating emails, let an email through at a specific time. Because I am often forgetting to let an email through at a later time.

**Comment by Matthijsy** [comment]
Would you like to do this on a specific email (when it is already in the queue)? Or to allow a mail to instant pass (if it is received on that date or already received) through on a specific date if it originates from a user in a specific group? Or based on some other condition?

**Comment by cmitz** [comment]
I think the best option is to, when moderating, allow a `deliver_at` option between now and 72 hours after the moderation request

Could be done with dynamic Sidekiq Scheduler jobs

**Comment by wilco375** [comment]
Yes, that would indeed be my idea, when an email is in the list to be moderated (queued), add an option  to accept it at a certain time instead of just instantly accepting it.

**Comment by cmitz** [comment]
If I may ask, what is your primary reason to delay an email?

**Comment by wilco375** [comment]
Primarily when a (most of the time unexpected) more important e-mail has to be sent before another email. In that case I want to delay the email I had planned to send that day until the end of the day, but then I often forget to send it at the end of the day.

**Comment by cmitz** [comment]
Okay, thanks for the answer. We should implement your suggestion, but to me it seems a little strange that we're still micromanaging members' emailboxes this way. But we've discussed that often enough, sorry to drag it up again

**Comment by wilco375** [comment]
A poll showed that people actually prefer getting multiple emails at once over receiving them spread across the day, so this feature is not very relevant then. So I will close the issue.
