### ISSUE TITLE
Do not require adress fields

### ISSUE THREAD

**Issue by cpbscholten** [csvalpha/amber-api#8]
Copied from alpha-banana-api (dutch):
@Matthijsy: Op dit moment zijn de adresgegevens van een gebruiker verplicht. Als we straks echter gebruikers gaan toevoegen die er alleen in staan voor het afhandelen van mail (zoals in de MISC lijst) wil je dat niet moeten invoeren.

Code ref: https://github.com/csvalpha/alpha-banana-api/blob/staging/app/models/user.rb#L30

@tcoenraad: Misschien moet dit worden opgesplitst worden in 2 typen users:

    full-fledged (user + persoon)
    light (user)

Dit is namelijk een direct gevolg van die samensmelting toen. Ik kan me echter voorstellen dat we dit onderscheid 'gewoon' willen maken. Wat voor nu ook kan natuurlijk is dat je een fake adres invult, maar dat is evenmin wenselijk.

@Matthijsy: Dat is inderdaad een optie. Maar de vraag is denk ik ook waarom we een adres bij een gebruiker/persoon zouden willen afdwingen

@cmitz Zouden we misschien een type lidmaatschap moeten introduceren bij Users? Dan kun je aan de hand daarvan validaties strenger maken.

We sturen sowieso wel eens post naar leden, waaronder het constitutiekaartje. Ik weet niet of dat verplicht is, maar we houden het in ieder geval bij met een doel: het ±3 keer per jaar sturen van post

@tcoenraad Misschien moeten we ook even de noodzaak opzoeken van het bijhouden van het adres wink Als iemand geen Digtus wil of een kaartje en er is verder geen noodzaak, moet dat denk ik ook kunnen. Maar als je leden moet kunnen identificeren aan óók het adres zou dat niet zo zijn.

**Comment by Matthijsy** [comment]
Since this only applies for a small amount of users it is better to enter 'unkown' for those then removing the enforcement. So we leave this in the current situation
