### ISSUE TITLE
Proposal: ask more information on User Export

### ISSUE THREAD

**Issue by cmitz** [csvalpha/amber-api#98]
Right now the export UI looks like this:
![afbeelding](https://user-images.githubusercontent.com/5594436/70134652-cda92880-1688-11ea-9527-cb96c277d9e4.png)

But I'd like to add one field:
>  When will you delete this export?

With a placeholder:
> I will delete this export 2 weeks after the activity on the 12nd of this month.

Or something like that

## Motivation

At the moment I still have a lot of questions when I see a database export email to `privacy@`. Most of the times the description is not very clear, and there has never been anyone that mentioned how long they will keep it. Asking for when it will be deleted forces a user to think of this.

When working on the screen anyway, we might rephrase the wording of the "Reason of the export" to provoke a more detailed description that is clear for everyone, also people not in the loop of the activities (like me).

**Comment by Matthijsy** [comment]
I agree with this issue. However I think that we do not need to add another field. We can probably just make more clear what we expect in the 'reason' field. This can also include the date of removal. 

We should maybe let the user ask the following questions:
- Who is going to access the data
- Why is the data needed (maybe still too broad)
- How will the data be stored
- When will the data be removed

**Comment by cmitz** [comment]
Okay, the form factor is open for discussion. Maybe another field is not required.

The questions, I agree with very much. 

> Why is the data needed (maybe still too broad)

Could be "What do you have to do, that you cannot do without this data?"

**Comment by Matthijsy** [comment]
Fixed in UI
